application: ballingerapp
version: 2
runtime: python
api_version: 1

handlers:
- url: /games
  script: viewgames.py

- url: /games/.*
  script: playrisk.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /newgame.*
  script: newGame.py

- url: /players
  script: notfound.py

- url: /newmap
  script: notfound.py

- url: /js
  static_dir: js

- url: /pics
  static_dir: pics

- url: /html
  static_dir: html

- url: /mapPic/.*
  script: mapPic.py

- url: /
  script: webapprisk.py

- url: /sign
  script: webapprisk.py

#- url: /.*
#  script: webapprisk.py

